### ISSUE TITLE
Fees set to zero

### ISSUE THREAD

**Issue by richardhundt** [alfredholmes/BinancePAMR#1]
Hi, I'm pretty sure you set your fees to zero when producing the MAMR plot. Either way, anything over 0.0002 (0.02%) seems to make a loss.

**Comment by alfredholmes** [comment]
There is a high dependence on the performance of the underlying assets (and therefore asset selection), I'm not sure what the original parameters were when I made the plots, but they might be worth updating.

**Comment by richardhundt** [comment]
I took your assets but with recent data. I'll try changing them, but I've been testing OLMAR, RMR and PAMR in simulations for the past week, with 1hr balancing frequency, including automatic parameter (grid) searching, and the charts always look amazing when you ignore the fees.

The closest I've come is picking uncorrelated assets and wrapping OLMAR in TCO (https://ink.library.smu.edu.sg/cgi/viewcontent.cgi?referer=&httpsredir=1&article=4761&context=sis_research) for some pretty modest gains.

EDIT: I also use BTC as the base currency for computing the price relatives instead of USD which helps

**Comment by alfredholmes** [comment]
Uncorrelated assets makes sense - if you have of order 100 assets (just pick all the available data) then MAMR seems to do quite well even with fees - I've tested this with actual trading and it should be profitable even with fees (comparing trading results with 0 fee prediction). The problem is its quite difficult to record all the data when trading. Also when downloading the data you need to be careful to not pick a biased sample - for example include Luna / coins that have gone to 0 in the data.

I think the best results I had was using an index (eg the total market cap) as the 'quote currency'.

**Comment by richardhundt** [comment]
Maybe it's because the current trading frequency in the code is set to `15m` but the chart says `12h`. In your live tests were you balancing twice daily?

**Comment by alfredholmes** [comment]
I expect the chart was made using 15m intervals, although I can't remember - I'll update the readme at some point and also improve the data acquisition etc so that its easier to test. The live tests were running at 5 minutes, but the moving average period parameter was quite large (about 300 I think, just over 1 day worth of data) to prevent over trading. I expect it doesn't really matter: 15 minutes with 100 periods is probably roughly the same as 5 minutes with 300 periods for example.

**Comment by richardhundt** [comment]
Thanks, you've given me some ideas! :+1:
